Many different relationships are easily conceptualized as a graph or network, where a graph is defined as a collection of nodes (entities) and edges (relationships) \cite{newman2003structure}. The field of graph theory, originally dating back to Euler in the 1700s, can be leveraged to better understand the underlying structure of these relationships. Examples of relationships include social networks (sociology), the world wide web (computer science), and protein networks (biology). 
Community detection in particular is one useful aspect of graph theory employed in analysis of each of these real-world applications to identify entities sharing a similar characteristic. Communities, also known as clusters or modules, are roughly defined as a group of nodes in a graph that share common properties \cite{fortunato2010community}. Typically the way a community shows up in a graph is a collection of nodes that has many edges to nodes 
\cc{perhaps replace with: edges connecting nodes} 
within but not many edges to nodes outside the collection. 

Current methodology for community detection often involves an algorithmic approach, and commonly partitions a graph into node clusters in an iterative manner before some stopping criterion. Tools such as igraph \cite{gc-igraph} and Gephi \cite{ICWSM09154} provide users with algorithmic community detection, and NodeXL \cite{hansen2010analyzing} provides detection algorithms for a similar concept called cliques. Algorithmic clustering is useful because it is an automated way to do community detection. However, determining the best algorithm is problematic because, as noted by Fortunato 
\cc{citation: (YYYY)}
, ``The main elements of the problem [graph clustering] themselves, i.e. the concepts of community and partition, are not rigorously defined, and require some degree of arbitrariness and/or common sense" \cite{fortunato2010community}
\cc{comment: move citation up}
. Since communities are often fuzzily-defined human concepts, an alternative approach is to leverage the human visual system
\cc{, which is capable of incorporating nuance, }
to identify communities
\cc{comment: delete rest of sentence}
, which is capable of incorporating nuance. The above tools do allow graph visualization, however they do not use humans as the vehicle for community detection.

To visualize a graph, a node-link diagram is used in which nodes are represented as a single point and a connecting edge is represented as a line connecting two points. The creation of this diagram involves assigning each node a cartesian coordinate, which is not an inherent property of a graph. This 
\cc{assigment}
is called a graph layout. McGrath, Blythe, and Krackhardt \cite{mcgrath1996seeing} found that the layout of a graph significantly affected the number of communities that users detected within a graph. Thus, when humans are the mechanism used 
\cc{replace with: when humans act as the mechanism}
to detect communities, special attention needs to be paid to the layout being used. The same study also found that location of a node spacially 
\cc{spatially}
relative to other nodes in a cluster has a significant effect on user ability to detect the community. The authors suggest a simple principle that will lead to clear depiction of a network: ``adjacent nodes must be placed near to each other if possible" \cite{mcgrath1996seeing}. One layout that adheres to this principle is a force-directed layout. This layout algorithm implements edges as fixed-distance geometric constraints, meaning that groups of nodes sharing multiple edges will be pulled in closer proximity. Dwyer, et. al. \cite{dwyer2009comparison} found the force-directed layout to be the best algorithmic layout as a platform to detect cliques
\cc{, which are one type of community}
. Further, they concluded that user-generated layouts similar to a force-based layout, but with symmetric layout within the cliques, allowed an even more accurate cluster recognition by users. Adaptation of the force-directed layout to incorporate a symmetric within cluster layout ``may be a difficult task for automatic algorithms, since maximal clique detection is NP-hard" \cite{dwyer2009comparison}. As cliques are similar to communities, in fact a clique is a community with perfect membership, we infer that adaptation of the force-directed layout to have symmetry within a community would be equivalently difficult. Thus, a force-directed layout is a good start 
\cc{perhaps delete: good; perhaps replace with: starting point}
for the user to be able to ``tweak" a layout into a more easily interpretable structure.

In complex or large graphs it can be difficult to glean any 
\cc{delete: any}
meaning from a graphical representation, even while using a force-directed layout. Dunne and Schneiderman \cite{dunne2013motif} introduce the idea of motifs, or repeated patterns in a graph
\cc{insert: to do blah blah}
.
One type of motif is a clique. 
\cc{comment: What's the purpose of this sentence? It seems to not fit with the flow of the surrounding sentences.}
By replacing the motifs with representations 
\cc{comment: what are representations? possibly give an example or include a picture of the process you're describing here in this paragraph}
and removing the correspding extra nodes and edges, the visualization will be more effective at revealing relationships. With fewer nodes and edges to display, visual complexity of the graph visualization is greatly reduced, allowing the user to analyze the network structure more accurately.

We used these findings to construct a community detection visualization tool, gravicom (available at \url{http://glimmer.rstudio.com/andeek/NetworkGraph/}). In this paper we will 
\cc{delete: will}
first give describe the user interface and functionality provided in gravicom. We then illustrate its use with two datasets, one
\cc{insert: comma}
a well known dataset of college football and the other 
\cc{insert: comma}
a network of political book co-purchasing. The third section of the paper details three important pieces of technology used to create gravicom. We finish the paper with a look forward at some further work than can be incorporated into the tool.
\cc{comment: This last sentence is unclear. do you mean further work that you and eric can incorporate into the tool? or further work that someone else could? in this sentence, passive tense makes meaning difficult to infer.}


